# Generated by Django 3.1.7 on 2021-03-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='first_name')),
                ('last_name', models.TextField(verbose_name='last_name')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(verbose_name='product_name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
            ],
            options={
                'verbose_name': 'CustomProduct',
                'verbose_name_plural': 'CustomProducts',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email_address')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='NonCustomProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(verbose_name='product_name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
            ],
            options={
                'verbose_name': 'CustomProduct',
                'verbose_name_plural': 'CustomProducts',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(verbose_name='paid')),
            ],
            options={
                'verbose_name': 'OrderStatus',
                'verbose_name_plural': 'OrderStatuss',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.noncustomproduct', verbose_name='non_custom_product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.customproduct', verbose_name='custom_product')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.TextField(verbose_name='order_number')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.customer', verbose_name='customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.orderstatus', verbose_name='status')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
