# Generated by Django 3.1.7 on 2021-03-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20210301_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noncustomproduct',
            options={'verbose_name': 'NonCustomProduct', 'verbose_name_plural': 'NonCustomProducts'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.noncustomproduct', verbose_name='non_custom_product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.customproduct', verbose_name='custom_product'),
        ),
    ]
